Make `normalize()` method to static in `CacheKeyNormalizer::class`.
yiisoft/cache pull request #140
Opened 2024-07-17 12:18 UTC by terabytesoftw

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌

2024-07-17 13:16 UTC, vjik requested changes
Need line in changelog and info in UPGRADE.md

2024-07-17 14:12 UTC, samdark approved these changes

2024-07-17 14:44 UTC, terabytesoftw commented
> Need line in changelog and info in UPGRADE.md

done.

2024-07-18 06:37 UTC, vjik approved these changes

2024-07-18 06:37 UTC, vjik commented on CHANGELOG.md
> +- Enh #139: Make `normalize()` method to static in `CacheKeyNormalizer::class` (@terabytesoftw)
```suggestion
- Chg #139: Make `normalize()` method static in `CacheKeyNormalizer` class (@terabytesoftw)
```

2024-07-18 06:37 UTC, vjik commented on UPGRADE.md
> +* Change method `normalize()` to static in `CacheKeyNormalizer` class.
```suggestion
# Upgrading Instructions for Yii Cache

This file contains the upgrade notes. These notes highlight changes that could break your
application when you upgrade the package from one version to another.

> **Important!** The following upgrading instructions are cumulative. That is, if you want
> to upgrade from version A to version C and there is version B between A and C, you need
> to following the instructions for both A and B.

## Upgrade from 3.x

- Change method `normalize()` to static in `CacheKeyNormalizer` class.
```

2024-07-18 06:40 UTC, merged